# Generated by Django 6.0.3 on 2026-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('association', 'Association'), ('company', 'Entreprise'), ('school', 'École'), ('public', 'Établissement public')], max_length=20, verbose_name='Type'),
        ),
    ]
