# Generated by Django 5.2.8 on 2026-01-15 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='badgeendorsement',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='badgehistory',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='structure',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, primary_key=True, serialize=False),
        ),
    ]
