# Generated by Django 5.2.8 on 2026-01-16 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_badge_uuid_alter_badgeendorsement_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='admins',
            field=models.ManyToManyField(related_name='structures_admins', to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs'),
        ),
    ]
