# Generated by Django 6.0.3 on 2026-03-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_structure_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='longitude',
        ),
    ]
