# Generated by Django 5.2.8 on 2026-01-16 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_structure_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='editors',
            field=models.ManyToManyField(related_name='structures_editors', to=settings.AUTH_USER_MODEL, verbose_name='Éditeurs'),
        ),
    ]
