# Generated by Django 6.0.3 on 2026-03-26 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge_generator', '0003_remove_generatedbadge_pictogram_and_more'),
        ('core', '0003_remove_structure_latitude_remove_structure_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='new_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='badge_generator.badgelevel', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='badge',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='badge_generator.badgecategory', verbose_name='Type'),
        ),
    ]
