# Generated by Django 6.0.3 on 2026-03-26 10:36

from django.db import migrations

def migrate_level_to_level(apps, schema_editor):
    Badge = apps.get_model('core', 'Badge')
    BadgeLevel = apps.get_model('badge_generator', 'BadgeLevel')

    # Get the levels, their names are populated in the 0004 from badge_generator
    beginner = BadgeLevel.objects.get(name="Découverte")
    intermediate = BadgeLevel.objects.get(name="Pratique")
    expert = BadgeLevel.objects.get(name="Maîtrise")

    for badge in Badge.objects.all():
        if badge.level is not None:
            if badge.level == "beginner":
                badge.new_level = beginner
            elif badge.level == "intermediate":
                badge.new_level = intermediate
            elif badge.level == "expert":
                badge.new_level = expert
        badge.save()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_badge_new_level_badge_type'),
        ('badge_generator', '0004_auto_20260326_1143'),
    ]

    operations = [
        migrations.RunPython(migrate_level_to_level),
    ]
