# Generated by Django 5.2.8 on 2026-01-23 11:03

import django.db.models.deletion
import pictures.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_structure_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='qr_code_height',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='qr_code_width',
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='assigned_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_badges', to='core.structure', verbose_name='Assigné par'),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='qr_code',
            field=pictures.models.PictureField(aspect_ratios=[None, '1/1'], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, height_field='qr_code_height', null=True, pixel_densities=[1, 2], upload_to='badges/qrcodes/', verbose_name='QR Code', width_field='qr_code_width'),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='qr_code_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='badgeassignment',
            name='qr_code_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='structures_users', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs'),
        ),
    ]
