# Generated by Django 6.0.1 on 2026-02-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_badge_qr_code_remove_badge_qr_code_height_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgeassignment',
            unique_together={('badge', 'assigned_structure', 'user')},
        ),
    ]
