# Generated by Django 6.0.3 on 2026-03-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260326_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='level',
        ),
    ]
