# Generated by Django 6.0.1 on 2026-02-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_badge_qr_code_remove_badge_qr_code_height_and_more'),
        ('mapview', '0002_mapviewconfig_marker_avatar_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='mapview.marker'),
        ),
    ]
