# Generated by Django 6.0.1 on 2026-02-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_badgeassignment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='valid_structures',
        ),
    ]
