# Generated by Django 6.0.3 on 2026-03-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_badge_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='new_level',
            new_name='level',
        ),
    ]
