# Generated by Django 6.0.1 on 2026-02-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_badge_valid_structures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeendorsement',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsments', to='core.structure', verbose_name='Structure'),
        ),
    ]
