# Generated by Django 6.0.3 on 2026-03-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_new_level_badge_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='type',
            new_name='category',
        ),
    ]
