# Generated by Django 6.0.4 on 2026-04-27 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_type_badge_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_badges', to=settings.AUTH_USER_MODEL, verbose_name='Attribué par'),
        ),
        migrations.AlterField(
            model_name='badgeassignment',
            name='assigned_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_badges', to='core.structure', verbose_name='Attribué par'),
        ),
    ]
