# Generated by Django 6.0.1 on 2026-02-17 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_badgeendorsement_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid7, primary_key=True, serialize=False)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.structure', verbose_name='Structure')),
            ],
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid7, primary_key=True, serialize=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='core.badge', verbose_name='Badge')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.course', verbose_name='Course')),
            ],
        ),
    ]
