# Generated by Django 6.0.1 on 2026-02-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_courseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.courseitem', verbose_name='Parent'),
        ),
    ]
