# Generated by Django 6.0.1 on 2026-02-23 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_courseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='is_dream_badge',
            field=models.BooleanField(default=False, verbose_name='Badge de rêve'),
        ),
        migrations.AddField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_badges', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
