# Generated by Django 6.0.2 on 2026-03-05 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_0006_structure_marker_0009_alter_badgeendorsement_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeCriteria',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid7, primary_key=True, serialize=False)),
                ('criteria', models.TextField(verbose_name="Critères d'attribution")),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_set', to='core.badge')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_criteria', to='core.structure')),
            ],
            options={
                'verbose_name': "Critères d'attribution",
                'verbose_name_plural': "Critères d'attribution",
                'unique_together': {('badge', 'structure')},
            },
        ),
    ]
