# Generated by Django 6.0.1 on 2026-02-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_badge_is_dream_badge_badge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='issuing_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_badges', to='core.structure', verbose_name='Structure émettrice'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('expert', 'Expert')], max_length=20, null=True, verbose_name='Niveau'),
        ),
    ]
