# Generated by Django 6.0.1 on 2026-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_courseitem_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.TextField(default='e', verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseitem',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='core.courseitem', verbose_name='Parent'),
        ),
    ]
