# Generated by Django 6.0.1 on 2026-02-27 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_badge_issuing_structure_alter_badge_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_course', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            bases=('core.course',),
        ),
    ]
