# Generated by Django 6.0.1 on 2026-02-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dreamcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='structure',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.structure', verbose_name='Structure'),
        ),
    ]
