# Generated by Django 6.0.1 on 2026-03-02 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_course_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamcourse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dream_course', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
