# Generated by Django 6.0.1 on 2026-03-05 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_dreamcourse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamcourse',
            name='course_ptr',
        ),
        migrations.RemoveField(
            model_name='dreamcourse',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='is_dream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dream_course', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='courseitem',
            unique_together={('course', 'badge')},
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('structure__isnull', True), ('user', True), _connector='OR'), name='structure_or_user_not_null'),
        ),
        migrations.DeleteModel(
            name='DreamCourse',
        ),
    ]
