# Generated by Django 6.0.1 on 2026-03-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_dreamcourse_course_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='structure_or_user_not_null',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('structure__isnull', False), ('user__isnull', False), _connector='OR'), name='structure_or_user_not_null'),
        ),
    ]
