# Generated by Django 6.0.1 on 2026-03-05 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_course_structure_or_user_not_null_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='badge',
            field=models.ForeignKey(default='019c670c-5e80-7783-9048-658f3e2328de', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.badge', verbose_name='Badge'),
            preserve_default=False,
        ),
    ]
