"""
Tags de template pour le generateur de badges.
On a besoin d'un tag pour afficher le SVG sans echappement HTML.
Custom template tags for the badge generator.

LOCALISATION : badge_generator/templatetags/badge_tags.py
"""

from django import template
from django.utils.safestring import mark_safe

register = template.Library()


@register.filter(name="safe_svg")
def safe_svg(svg_content):
    """
    On marque le contenu SVG comme sur pour l'affichage.
    Django echappe le HTML par defaut. Ce filtre dit a Django
    que le contenu SVG est sur et peut etre affiche tel quel.
    Mark SVG content as safe for display (bypass Django escaping).

    ATTENTION SECURITE : ce filtre ne doit etre utilise QUE pour du SVG
    genere par le moteur svg_engine.py. Ne jamais l'utiliser sur du
    contenu fourni directement par l'utilisateur sans sanitization.
    Les textes utilisateur sont deja echappes par _escape_svg_text()
    dans svg_engine.py avant d'etre integres au SVG.

    SECURITY WARNING: only use this filter on SVG generated by svg_engine.py.
    Never use on raw user input. User text is already escaped by
    _escape_svg_text() in svg_engine.py before being embedded in the SVG.
    """
    if not svg_content:
        return ""
    return mark_safe(svg_content)
