# Generated by Django 6.0.1 on 2026-02-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapViewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_lat', models.FloatField(default=45.766543)),
                ('center_lng', models.FloatField(default=4.879528)),
            ],
            options={
                'verbose_name': 'Map View Configuration',
                'verbose_name_plural': 'Map View Configurations',
            },
        ),
        migrations.AddField(
            model_name='marker',
            name='avatar_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='avatar_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
