# Generated by Django 6.0.3 on 2026-03-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0002_mapviewconfig_marker_avatar_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='lng',
            new_name='longitude',
        ),
    ]
