# Generated by Django 6.0.3 on 2026-03-09 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant unique')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('icon', models.CharField(blank=True, default='🏷️', max_length=10, verbose_name='Icône')),
                ('color', models.CharField(default='#4A90D9', help_text='Code couleur hexadécimal, par exemple #4A90D9', max_length=7, verbose_name='Couleur principale')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de badge',
                'verbose_name_plural': 'Catégories de badges',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BadgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant unique')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du niveau')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('rank', models.PositiveIntegerField(default=1, help_text='1 = débutant, 5 = expert', verbose_name='Rang')),
                ('shape_sides', models.PositiveIntegerField(default=6, help_text='3 = triangle, 4 = carré, 5 = pentagone, 6 = hexagone, 0 = cercle', verbose_name='Nombre de côtés de la forme')),
            ],
            options={
                'verbose_name': 'Niveau de badge',
                'verbose_name_plural': 'Niveaux de badges',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Pictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant unique')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pictogramme')),
                ('svg_content', models.TextField(help_text='Le contenu SVG du pictogramme (balises path, circle, etc.)', verbose_name='Code SVG')),
                ('tags', models.CharField(blank=True, default='', help_text='Séparer les mots-clés par des virgules', max_length=200, verbose_name='Mots-clés')),
                ('categories', models.ManyToManyField(blank=True, related_name='pictograms', to='badge_generator.badgecategory', verbose_name='Catégories associées')),
            ],
            options={
                'verbose_name': 'Pictogramme',
                'verbose_name_plural': 'Pictogrammes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant unique')),
                ('title', models.CharField(max_length=100, verbose_name='Titre du badge')),
                ('subtitle', models.CharField(blank=True, default='', max_length=100, verbose_name='Sous-titre')),
                ('primary_color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Couleur secondaire')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Couleur du texte')),
                ('svg_content', models.TextField(blank=True, default='', verbose_name='Code SVG généré')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_badges', to='badge_generator.badgecategory', verbose_name='Catégorie')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_badges', to='badge_generator.badgelevel', verbose_name='Niveau')),
                ('pictogram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_badges', to='badge_generator.pictogram', verbose_name='Pictogramme')),
            ],
            options={
                'verbose_name': 'Badge généré',
                'verbose_name_plural': 'Badges générés',
                'ordering': ['-created_at'],
            },
        ),
    ]
