# Generated by Django 6.0.3 on 2026-03-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge_generator', '0002_add_dome_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedbadge',
            name='pictogram',
        ),
        migrations.RemoveField(
            model_name='badgelevel',
            name='shape_sides',
        ),
        migrations.RemoveField(
            model_name='generatedbadge',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='generatedbadge',
            name='text_color',
        ),
        migrations.DeleteModel(
            name='Pictogram',
        ),
    ]
