"""
Formes SVG pour les badges.
Chaque forme est un chemin SVG (attribut "d") dans un espace 500x500.
Toutes les formes sont calculees une seule fois au chargement du module.
Le Dome propose 8 formes differentes, une par categorie.
On les rend toutes disponibles a l'utilisateur.

Il y a deux familles de formes :
- Les formes calculees (starburst, circle, hexagon, etc.) : generees par des fonctions Python.
- Les formes du Dome (dome_cp, dome_sv, etc.) : importees depuis les SVG du generateur du Dome,
  puis redimensionnees pour tenir dans notre espace 500x500.

SVG shapes for badges.
Each shape is an SVG path ("d" attribute) in a 500x500 coordinate space.
All shapes are computed once at module load.
Le Dome offers 8 different shapes, one per category.
We make all of them available to the user.

Two families of shapes:
- Computed shapes (starburst, circle, hexagon, etc.): generated by Python functions.
- Dome shapes (dome_cp, dome_sv, etc.): imported from the Dome generator SVGs,
  then rescaled to fit our 500x500 space.

LOCALISATION : badge_generator/shapes.py
"""

import math
import re


# ============================================================================
# Constantes communes a toutes les formes.
# Common constants for all shapes.
# ============================================================================

BADGE_SIZE = 500
CENTER_X = BADGE_SIZE / 2
CENTER_Y = BADGE_SIZE / 2


# ============================================================================
# Fonction utilitaire : construire un polygone arrondi.
# On calcule les sommets du polygone, puis on les relie
# par des courbes de bezier pour arrondir les coins.
#
# Utility: build a rounded polygon.
# Compute polygon vertices, connect them with bezier curves.
# ============================================================================

def _build_rounded_polygon_path(
    number_of_sides,
    radius,
    tension=0.35,
    center_x=CENTER_X,
    center_y=CENTER_Y,
):
    """
    On fabrique un polygone regulier avec des coins arrondis.
    Le premier sommet est en haut (a midi).

    Build a regular polygon with rounded corners.
    First vertex is at the top (12 o'clock).
    """

    # On calcule tous les sommets du polygone.
    # Compute all polygon vertices.
    all_vertices = []

    for vertex_index in range(number_of_sides):
        # L'angle de chaque sommet. On commence en haut (-90 degres).
        # Angle for each vertex, starting from top (-90 degrees).
        angle_in_radians = (
            2 * math.pi * vertex_index / number_of_sides
        ) - (math.pi / 2)

        vertex_x = center_x + radius * math.cos(angle_in_radians)
        vertex_y = center_y + radius * math.sin(angle_in_radians)

        # Direction tangente (perpendiculaire au rayon, sens horaire).
        # Tangent direction (perpendicular to radius, clockwise).
        tangent_x = -math.sin(angle_in_radians)
        tangent_y = math.cos(angle_in_radians)

        all_vertices.append({
            "x": vertex_x,
            "y": vertex_y,
            "tx": tangent_x,
            "ty": tangent_y,
        })

    # On construit le chemin SVG avec des courbes de bezier.
    # Build SVG path with bezier curves.
    path_parts = []
    first_vertex = all_vertices[0]
    path_parts.append(f"M{first_vertex['x']:.1f} {first_vertex['y']:.1f}")

    for vertex_index in range(number_of_sides):
        current_vertex = all_vertices[vertex_index]
        next_vertex = all_vertices[(vertex_index + 1) % number_of_sides]

        delta_x = next_vertex["x"] - current_vertex["x"]
        delta_y = next_vertex["y"] - current_vertex["y"]
        distance = math.sqrt(delta_x * delta_x + delta_y * delta_y)
        arm_length = distance * tension

        cp1_x = current_vertex["x"] + current_vertex["tx"] * arm_length
        cp1_y = current_vertex["y"] + current_vertex["ty"] * arm_length

        cp2_x = next_vertex["x"] - next_vertex["tx"] * arm_length
        cp2_y = next_vertex["y"] - next_vertex["ty"] * arm_length

        path_parts.append(
            f"C{cp1_x:.1f} {cp1_y:.1f} "
            f"{cp2_x:.1f} {cp2_y:.1f} "
            f"{next_vertex['x']:.1f} {next_vertex['y']:.1f}"
        )

    path_parts.append("Z")
    return " ".join(path_parts)


# ============================================================================
# Fonction utilitaire : construire une etoile arrondie.
# Les etoiles ont des pointes (rayon exterieur) et des creux (rayon interieur).
# On les relie par des courbes de bezier pour un rendu doux.
#
# Utility: build a rounded star.
# Stars have peaks (outer radius) and valleys (inner radius).
# Connected with bezier curves for a smooth look.
# ============================================================================

def _build_rounded_star_path(
    number_of_peaks,
    outer_radius,
    inner_radius,
    tension=0.38,
    center_x=CENTER_X,
    center_y=CENTER_Y,
):
    """
    On fabrique une etoile avec des pointes arrondies.
    La premiere pointe est en haut.

    Build a star with rounded peaks. First peak is at top.
    """

    # On calcule tous les points : pointe, creux, pointe, creux...
    # Compute all points: peak, valley, peak, valley...
    total_points = number_of_peaks * 2
    all_points = []

    for point_index in range(total_points):
        angle = (2 * math.pi * point_index / total_points) - (math.pi / 2)
        is_peak = (point_index % 2 == 0)
        radius = outer_radius if is_peak else inner_radius

        point_x = center_x + radius * math.cos(angle)
        point_y = center_y + radius * math.sin(angle)
        tangent_x = -math.sin(angle)
        tangent_y = math.cos(angle)

        all_points.append({
            "x": point_x,
            "y": point_y,
            "tx": tangent_x,
            "ty": tangent_y,
        })

    # On construit le chemin SVG avec des courbes de bezier.
    # Build SVG path with bezier curves.
    path_parts = []
    first_point = all_points[0]
    path_parts.append(f"M{first_point['x']:.1f} {first_point['y']:.1f}")

    for point_index in range(total_points):
        current = all_points[point_index]
        next_point = all_points[(point_index + 1) % total_points]

        delta_x = next_point["x"] - current["x"]
        delta_y = next_point["y"] - current["y"]
        distance = math.sqrt(delta_x * delta_x + delta_y * delta_y)
        arm_length = distance * tension

        cp1_x = current["x"] + current["tx"] * arm_length
        cp1_y = current["y"] + current["ty"] * arm_length
        cp2_x = next_point["x"] - next_point["tx"] * arm_length
        cp2_y = next_point["y"] - next_point["ty"] * arm_length

        path_parts.append(
            f"C{cp1_x:.1f} {cp1_y:.1f} "
            f"{cp2_x:.1f} {cp2_y:.1f} "
            f"{next_point['x']:.1f} {next_point['y']:.1f}"
        )

    path_parts.append("Z")
    return " ".join(path_parts)


# ============================================================================
# Forme : Cercle.
# Le cercle est la forme la plus simple. C'est la forme du Savoir-Vivre (Sv)
# dans Le Dome.
#
# Shape: Circle. Simplest shape. Used by Savoir-Vivre (Sv) in Le Dome.
# ============================================================================

def _build_circle_path(radius=230, center_x=CENTER_X, center_y=CENTER_Y):
    """
    On fabrique un cercle parfait en SVG.
    On utilise 2 arcs de cercle qui se rejoignent.

    Build a perfect SVG circle using 2 arcs.
    """
    top_y = center_y - radius
    bottom_y = center_y + radius

    return (
        f"M{center_x:.1f} {top_y:.1f} "
        f"A{radius} {radius} 0 1 1 {center_x:.1f} {bottom_y:.1f} "
        f"A{radius} {radius} 0 1 1 {center_x:.1f} {top_y:.1f} Z"
    )


# ============================================================================
# Forme : Bouclier / Ecusson.
# Un ecusson classique avec un haut arrondi et un bas en pointe.
# C'est une forme courante pour les badges et les blasons.
#
# Shape: Shield / Crest.
# Classic shield with rounded top and pointed bottom.
# ============================================================================

def _build_shield_path(center_x=CENTER_X, center_y=CENTER_Y):
    """
    On fabrique un ecusson en bezier.
    Le haut est arrondi, le bas se termine en pointe.

    Build a shield shape with bezier curves.
    Rounded top, pointed bottom.
    """
    # Dimensions de l'ecusson.
    # Shield dimensions.
    half_width = 200
    top_y = center_y - 210
    bottom_y = center_y + 230
    shoulder_y = center_y - 120
    waist_y = center_y + 60

    left_x = center_x - half_width
    right_x = center_x + half_width

    return (
        f"M{left_x:.1f} {shoulder_y:.1f} "
        f"L{left_x:.1f} {top_y:.1f} "
        f"Q{left_x:.1f} {top_y - 50:.1f} {center_x:.1f} {top_y - 50:.1f} "
        f"Q{right_x:.1f} {top_y - 50:.1f} {right_x:.1f} {top_y:.1f} "
        f"L{right_x:.1f} {shoulder_y:.1f} "
        f"L{right_x:.1f} {waist_y:.1f} "
        f"Q{right_x:.1f} {bottom_y - 40:.1f} {center_x:.1f} {bottom_y:.1f} "
        f"Q{left_x:.1f} {bottom_y - 40:.1f} {left_x:.1f} {waist_y:.1f} "
        f"Z"
    )


# ============================================================================
# On calcule toutes les formes une seule fois au chargement du module.
# On les stocke dans un dictionnaire pour y acceder rapidement.
#
# Compute all shapes once at module load. Store in dict for quick access.
# ============================================================================

ALL_SHAPES = {
    "starburst": {
        "name": "Starburst",
        "description": "Étoile rayonnante (20 pointes)",
        "path": _build_rounded_star_path(
            number_of_peaks=20,
            outer_radius=230,
            inner_radius=200,
            tension=0.38,
        ),
    },
    "circle": {
        "name": "Cercle",
        "description": "Cercle classique",
        "path": _build_circle_path(radius=230),
    },
    "star5": {
        "name": "Étoile 5",
        "description": "Étoile à 5 branches",
        "path": _build_rounded_star_path(
            number_of_peaks=5,
            outer_radius=235,
            inner_radius=140,
            tension=0.25,
        ),
    },
    "star8": {
        "name": "Étoile 8",
        "description": "Étoile à 8 branches",
        "path": _build_rounded_star_path(
            number_of_peaks=8,
            outer_radius=232,
            inner_radius=170,
            tension=0.30,
        ),
    },
    "hexagon": {
        "name": "Hexagone",
        "description": "Hexagone arrondi",
        "path": _build_rounded_polygon_path(
            number_of_sides=6,
            radius=235,
            tension=0.30,
        ),
    },
    "shield": {
        "name": "Écusson",
        "description": "Forme blason / écusson",
        "path": _build_shield_path(),
    },
    "pentagon": {
        "name": "Pentagone",
        "description": "Pentagone arrondi",
        "path": _build_rounded_polygon_path(
            number_of_sides=5,
            radius=235,
            tension=0.30,
        ),
    },
    "diamond": {
        "name": "Losange",
        "description": "Losange arrondi",
        "path": _build_rounded_polygon_path(
            number_of_sides=4,
            radius=240,
            tension=0.35,
        ),
    },
}

# ============================================================================
# Formes du Dome.
# Le generateur du Dome (openbadges.ledome.info) utilise 8 formes distinctes,
# une par categorie de badge : CP, SV, SF, SE, XP, PJ, GP, PC.
# Chaque forme est definie par un chemin SVG dans un viewBox specifique.
# On les normalise toutes vers notre espace 500x500.
#
# Dome shapes.
# The Dome generator uses 8 distinct shapes, one per badge category.
# Each is defined in its own viewBox. We normalize them to 500x500.
# ============================================================================


def _rescale_dome_path(
    path_d,
    viewbox_size,
    group_translate_x=0,
    group_translate_y=0,
):
    """
    On normalise un chemin SVG du Dome vers notre espace 500x500.
    Le Dome utilise des viewBox de tailles differentes (840, 850, 888, 1247).
    On redimensionne toutes les coordonnees pour que le badge s'affiche
    correctement dans un carre de 500x500 pixels.

    Les coordonnees absolues (commandes majuscules) sont translatees puis mises a l'echelle.
    Les coordonnees relatives (commandes minuscules) sont seulement mises a l'echelle.
    Exception : le premier "m" est traite comme absolu (spec SVG).

    Normalize a Dome SVG path to our 500x500 coordinate space.
    Absolute coords (uppercase commands) get translated then scaled.
    Relative coords (lowercase commands) get scaled only.
    Exception: first "m" is treated as absolute (SVG spec).
    """

    target_size = 500
    scale = target_size / viewbox_size

    # On decoupe le chemin en tokens : lettres de commande et nombres.
    # Tokenize path into command letters and numbers.
    token_pattern = (
        r'[MmCcLlHhVvZz]'
        r'|[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?'
    )
    tokens = re.findall(token_pattern, path_d)

    result_parts = []
    index = 0
    current_command = None
    is_first_moveto = True

    while index < len(tokens):
        token = tokens[index]

        # Si c'est Z ou z, on le garde tel quel (fermer le chemin).
        # Z/z closes the path, no coordinates.
        if token in ('Z', 'z'):
            result_parts.append(token)
            index += 1
            continue

        # Si c'est une lettre de commande, on la garde et on avance.
        # If it's a command letter, store it and advance.
        if token.isalpha():
            current_command = token
            result_parts.append(token)
            index += 1
            continue

        # C'est un nombre. On le traite selon la commande en cours.
        # It's a number. Process based on current command.

        # Le premier "m" est traite comme un "M" absolu (spec SVG).
        # First "m" is treated as absolute "M" (SVG spec).
        if current_command == 'm' and is_first_moveto:
            treat_as_absolute = True
            is_first_moveto = False
        elif current_command and current_command.isupper():
            treat_as_absolute = True
        else:
            treat_as_absolute = False

        command_upper = current_command.upper() if current_command else 'M'

        # --- Commandes avec 2 coordonnees (x, y) ---
        # Commands with 2 coordinates (x, y): M, L
        if command_upper in ('M', 'L'):
            x_value = float(tokens[index])
            y_value = float(tokens[index + 1])
            if treat_as_absolute:
                x_value = (x_value + group_translate_x) * scale
                y_value = (y_value + group_translate_y) * scale
            else:
                x_value = x_value * scale
                y_value = y_value * scale
            result_parts.append(f'{x_value:.3f},{y_value:.3f}')
            index += 2

        # --- Courbe cubique de Bezier (6 coordonnees) ---
        # Cubic bezier curve (6 coordinates): C
        elif command_upper == 'C':
            for _bezier_point in range(3):
                x_value = float(tokens[index])
                y_value = float(tokens[index + 1])
                if treat_as_absolute:
                    x_value = (x_value + group_translate_x) * scale
                    y_value = (y_value + group_translate_y) * scale
                else:
                    x_value = x_value * scale
                    y_value = y_value * scale
                result_parts.append(f'{x_value:.3f},{y_value:.3f}')
                index += 2

        # --- Ligne horizontale (1 coordonnee x) ---
        # Horizontal line (1 x coordinate): H
        elif command_upper == 'H':
            x_value = float(tokens[index])
            if treat_as_absolute:
                x_value = (x_value + group_translate_x) * scale
            else:
                x_value = x_value * scale
            result_parts.append(f'{x_value:.3f}')
            index += 1

        # --- Ligne verticale (1 coordonnee y) ---
        # Vertical line (1 y coordinate): V
        elif command_upper == 'V':
            y_value = float(tokens[index])
            if treat_as_absolute:
                y_value = (y_value + group_translate_y) * scale
            else:
                y_value = y_value * scale
            result_parts.append(f'{y_value:.3f}')
            index += 1

        # --- Commande non geree, on passe le nombre tel quel. ---
        # Unhandled command, pass number as-is.
        else:
            result_parts.append(token)
            index += 1

    return ' '.join(result_parts)


# ----------------------------------------------------------------------------
# Chemins SVG bruts du Dome, extraits des fichiers SVG originaux.
# On stocke le chemin, la taille du viewBox original,
# et le translate du groupe parent dans le SVG original.
#
# Raw Dome SVG paths, extracted from original SVG files.
# Stored with original viewBox size and parent group translate.
# ----------------------------------------------------------------------------

# CP — Competence : etoile organique aux bords ondules.
# CP — Competence: organic star with wavy edges.
_DOME_CP_RAW_PATH = (
    "m 617.41635,172.08984 c -51.45083,0.29333 -102.74095,28.76298 "
    "-128.87695,85.26563 -36.2373,78.3414 -106.83827,132.89908 "
    "-188.79297,145.89648 -118.2173,18.7466 -164.59137,171.86157 "
    "-78.47265,259.10157 l 40.73828,41.26953 c 34.1973,34.6427 "
    "49.9992,84.74457 42.2539,133.98047 l -9.22851,58.65429 "
    "C 275.53215,1020.2458 399.7602,1114.0041 505.2562,1054.916 "
    "l 49.90625,-27.9512 c 41.8934,-23.4653 92.09856,-23.7509 "
    "134.25586,-0.7656 l 50.2207,27.3809 h 0.002 "
    "c 106.16366,57.8783 229.31312,-37.2883 208.39454,-161.04494 "
    "l -9.89649,-58.54493 c -8.3053,-49.1453 6.92266,-99.42437 "
    "40.72266,-134.45507 l 40.26758,-41.73047 "
    "c 85.1174,-88.2147 36.9996,-240.79206 -81.42579,-258.18946 "
    "l -56.01953,-8.23046 c -47.0267,-6.9094 -87.82314,-37.69744 "
    "-109.08984,-82.33204 L 747.2582,255.88086 "
    "C 720.47885,199.67951 668.86724,171.79652 617.4164,172.08984 Z"
)
_DOME_CP_VIEWBOX = 1247.2441

# SV — Savoir : cercle parfait.
# SV — Knowledge: perfect circle.
_DOME_SV_RAW_PATH = (
    "m 421.125,738.355 c -163.399,0 -296.299,-132.9 -296.299,-296.257 "
    "0,-163.357 132.9,-296.257 296.299,-296.257 163.381,0 296.285,132.9 "
    "296.285,296.257 0,163.357 -138.237,296.257 -296.285,296.257 z"
)
_DOME_SV_VIEWBOX = 840.0
_DOME_SV_TRANSLATE_X = -6.5414687

# SF — Savoir-faire : forme organique irreguliere.
# SF — Know-how: irregular organic shape.
_DOME_SF_RAW_PATH = (
    "m 274.809,703.227 c -1.966,-0.43 -3.815,-1.113 -5.504,-2.027 "
    "l -7.873,-4.272 c -10.632,-5.763 -15.877,-16.04 -23.14,-30.257 "
    "-9.563,-18.741 -21.466,-42.053 -50.663,-57.897 l -5.439,-2.961 "
    "-57.046,-22.501 -3.821,-2.486 -0.46,-0.237 "
    "c -2.623,-1.663 -9.375,-10.749 -12.848,-18.058 "
    "-2.913,-6.225 -3.598,-9.917 -2.148,-20.792 "
    "1.167,-8.747 2.911,-15.969 4.601,-22.951 "
    "3.511,-14.536 7.143,-29.559 3.955,-52.146 "
    "-3.019,-21.421 -14.157,-38.303 -23.984,-53.203 "
    "-2.711,-4.104 -5.441,-8.222 -8.017,-12.48 "
    "-4.756,-7.861 -7.949,-14.329 -9.149,-22.292 "
    "-0.741,-4.871 0.684,-17.507 2.848,-21.57 l 4.724,-8.849 "
    "c 2.349,-3.552 17.499,-16.679 24.032,-20.695 "
    "9.965,-6.06 29.163,-21.891 38.035,-38.441 l 4.767,-8.975 "
    "c 8.247,-15.439 12.141,-47.821 12.841,-54.157 "
    "1.591,-14.516 2.073,-18.908 7.837,-29.097 "
    "5.019,-9.397 13.338,-18.846 38.157,-19.864 "
    "7.513,-0.319 13.982,0.232 20.826,0.812 "
    "13.765,1.184 27.922,2.401 47.087,-3.488 "
    "25.455,-7.808 34.487,-16.759 45.92,-28.086 "
    "3.993,-3.958 8.447,-8.368 14.43,-13.535 "
    "10.205,-8.877 16.569,-12.262 20.123,-13.546 "
    "5.223,-1.933 5.504,-1.917 7.342,-1.825 l 5,0.214 "
    "c 6.18,0.269 10.159,0.441 13.649,1.204 "
    "2.773,0.606 5.178,1.376 10.258,4.136 "
    "2.609,1.523 12.168,9.8 15.311,12.523 "
    "2.504,2.168 4.615,3.992 6.135,5.24 "
    "1.479,1.232 3.482,3.063 5.682,5.081 "
    "7.627,6.983 15.027,13.757 21.596,17.29 l 7.732,4.219 "
    "c 7.297,3.958 14.947,6.772 23.432,8.627 "
    "15.764,3.445 31.363,2.767 45.125,2.17 "
    "11.275,-0.488 21.928,-0.946 30.504,0.928 "
    "3.199,0.699 5.928,1.674 8.354,2.992 "
    "17.021,9.232 19.639,23.2 23.139,49.14 l 0.105,0.75 "
    "c 0.482,3.543 0.967,7.109 1.518,10.689 "
    "2.057,13.588 7.553,33.233 15.195,46.39 "
    "9.949,17.145 24.463,29.29 37.271,39.994 "
    "14.283,11.935 26.596,22.236 31.451,37.086 "
    "3.1,10.294 -0.439,17.531 -11.143,36.884 "
    "-1.904,3.438 -3.873,6.998 -5.891,10.789 "
    "L 631.011,443 c -14.045,26.324 -6.578,52.92 0.014,76.387 "
    "4.592,16.366 8.924,31.783 3.777,41.433 "
    "-8.619,16.152 -20.396,25.397 -40.637,31.899 "
    "-5.42,1.746 -10.633,3.514 -15.947,5.32 l -9.785,3.313 "
    "c -15.646,5.174 -22.473,11.428 -29.695,18.042 "
    "-2.328,2.142 -4.918,4.521 -8.348,7.254 "
    "-11.178,8.914 -18.34,23.295 -24.654,35.976 "
    "-1.518,3.045 -2.834,5.694 -4.135,8.129 l -1.889,3.547 "
    "c -16.189,30.383 -34.559,30.714 -48.756,27.611 "
    "-7.873,-1.721 -16.699,-5.226 -26.25,-10.41 l -1.951,-1.07 "
    "-34.584,-9.884 -2.219,-0.136 "
    "c -10.516,-0.634 -22.397,-0.648 -38.188,3.404 "
    "-2.329,0.596 -4.696,1.153 -7.052,1.691 "
    "-8.219,1.906 -17.497,4.049 -26.595,8.467 "
    "-6.263,3.045 -25.373,12.3 -39.308,9.254 z"
)
_DOME_SF_VIEWBOX = 840.0
_DOME_SF_TRANSLATE_X = 56.059658
_DOME_SF_TRANSLATE_Y = -1.8195287

# SE — Savoir-etre : rectangle arrondi.
# SE — Being/Attitude: rounded rectangle.
_DOME_SE_RAW_PATH = (
    "M 586.615,203.177 C 528.5,148.971 450.58,115.783 364.859,115.783 "
    "c -85.722,0 -163.64,33.188 -221.743,87.394 "
    "-11.891,11.699 -16.655,24.214 -16.655,46.113 v 326.302 "
    "c 0,21.887 4.765,34.42 16.655,46.127 "
    "58.104,54.189 136.021,87.375 221.743,87.375 "
    "85.721,0 163.641,-33.186 221.756,-87.375 "
    "11.896,-11.707 16.643,-24.24 16.643,-46.127 V 249.29 "
    "c -0.001,-21.899 -4.748,-34.414 -16.643,-46.113 z"
)
_DOME_SE_VIEWBOX = 888.18899
_DOME_SE_TRANSLATE_X = 79.039
_DOME_SE_TRANSLATE_Y = 28.749798

# XP — Experience : hexagone allonge / losange aplati.
# XP — Experience: elongated hexagon / flattened diamond.
_DOME_XP_RAW_PATH = (
    "m 778.218,417.349 c -0.048,4.907 -0.524,10.207 -1.412,13.588 "
    "L 739.778,583.07 c -0.714,2.703 -4.982,6.897 -7.498,7.364 "
    "l -293.727,59.811 c -3.307,0.609 -8.156,0.963 -13.25,0.963 "
    "v 0 c -5.091,0 -9.939,-0.354 -13.247,-0.963 "
    "L 118.327,590.434 c -2.514,-0.467 -6.783,-4.661 -7.497,-7.364 "
    "L 73.802,430.937 c -0.886,-3.381 -1.362,-8.681 -1.411,-13.588 "
    "v 0 c 0.048,-4.907 0.524,-10.208 1.411,-13.589 "
    "l 37.029,-152.134 c 0.713,-2.704 4.982,-6.898 7.497,-7.364 "
    "l 293.729,-59.811 c 3.308,-0.61 8.156,-0.961 13.247,-0.961 "
    "v 0 c 5.093,0 9.943,0.352 13.25,0.961 "
    "l 293.727,59.811 c 2.516,0.466 6.784,4.661 7.498,7.364 "
    "l 37.028,152.134 c 0.886,3.381 1.363,8.681 1.411,13.589 z"
)
_DOME_XP_VIEWBOX = 850.0
_DOME_XP_TRANSLATE_X = -0.57932694

# PJ — Projet : hexagone pointu / forme losange allonge verticalement.
# PJ — Project: pointed hexagon / vertically elongated diamond.
_DOME_PJ_RAW_PATH = (
    "m 426.33,701.628 c -4.464,0 -7.848,-1.037 -9.525,-2.008 "
    "L 176.458,560.861 c -4.631,-2.679 -9.536,-11.168 -9.536,-16.518 "
    "V 266.822 c 0,-5.35 4.905,-13.839 9.536,-16.513 "
    "L 416.797,111.55 c 1.678,-0.971 5.063,-2.007 9.533,-2.007 "
    "4.47,0 7.855,1.037 9.532,2.003 l 240.343,138.759 "
    "c 4.636,2.678 9.533,11.168 9.533,16.518 v 277.521 "
    "c 0,5.35 -4.897,13.839 -9.533,16.514 "
    "L 435.87,699.616 c -1.684,0.975 -5.069,2.012 -9.54,2.012 z"
)
_DOME_PJ_VIEWBOX = 888.18899
_DOME_PJ_TRANSLATE_X = -1.18601
_DOME_PJ_TRANSLATE_Y = 34.28187

# GP — Groupe : forme organique avec courbes fluides.
# GP — Group/Community: organic shape with flowing curves.
_DOME_GP_RAW_PATH = (
    "m 423.73,681.347 c -19.09126,-14.57011 -37.45193,-29.66081 "
    "-57.849,-37.585 -18.42,-7.021 -36.83,-14.072 -55.381,-20.737 "
    "-15.076,-5.418 -30.576,-9.717 -45.467,-15.58 "
    "-11.408,-4.491 -22.871,-9.568 -33.064,-16.275 "
    "-28.578,-18.803 -44.348,-45.673 -46.42,-80.052 "
    "-0.592,-9.837 -0.324,-19.73 -0.328,-29.598 "
    "-0.021,-69.081 -0.01,-138.162 -0.014,-207.243 "
    "-0.002,-9.87 -0.061,-19.738 -0.045,-29.607 "
    "0.055,-34.956 -4.541,-68.869 -21.598,-100.176 "
    "-3.297,-6.049 -2.027,-12.834 2.666,-16.775 "
    "14.16,-11.889 28.412,-23.672 42.855,-35.213 "
    "4.063,-3.246 9.256,-3.568 13.971,-1.259 "
    "38.408,18.817 79.773,24.294 121.709,28.342 "
    "57.98,5.598 115.824,4.556 173.607,-1.464 "
    "35.643,-3.713 70.9,-9.78 103.48,-25.971 "
    "4.764,-2.368 10.232,-3.719 14.018,-0.69 "
    "16.318,13.053 32.131,26.746 47.891,40.477 "
    "1.494,1.301 1.561,4.465 1.855,6.819 "
    "0.135,1.081 -0.65,2.364 -1.236,3.437 "
    "-18.91,34.641 -23.082,72.458 -23.871,110.983 "
    "-0.201,9.865 -0.059,19.737 -0.06,29.605 "
    "-0.005,66.614 -0.001,133.229 -0.013,199.842 "
    "0,8.635 -0.137,17.271 -0.092,25.905 "
    "0.215,39.816 -19.646,67.667 -52.666,87.246 "
    "-8.418,4.99 -17.738,8.624 -26.945,12.073 "
    "-13.85,5.188 -27.965,9.667 -41.969,14.44 "
    "-10.5,3.578 -21.084,6.931 -31.492,10.756 "
    "-42.276,15.536 -49.858,19.963 -83.542,48.3 z"
)
_DOME_GP_VIEWBOX = 850.39371
_DOME_GP_TRANSLATE_X = 0.45366005
_DOME_GP_TRANSLATE_Y = 18.132028

# PC — Parcours : bouclier avec encoches laterales.
# PC — Journey/Course: shield with side notches.
_DOME_PC_RAW_PATH = (
    "m 428.791,111.939 c -0.019,0 -0.051,0 -0.076,0 v 0.032 "
    "c -17.186,0.318 -36.207,7.442 -54.628,14.36 "
    "-14.804,5.56 -30.104,11.327 -41.793,12.484 "
    "l -1.201,0.123 -1.079,-0.354 "
    "c -3.614,-1.202 -10.563,-4.915 -15.482,-8.283 "
    "l -6.813,-4.655 -105.501,51.097 v 464.374 "
    "l 105.501,51.104 6.813,-4.66 "
    "c 4.919,-3.368 11.868,-7.078 15.482,-8.271 "
    "l 1.079,-0.357 1.201,0.116 "
    "c 11.689,1.166 26.989,6.923 41.793,12.476 "
    "18.421,6.923 37.442,14.049 54.628,14.369 v 0.034 "
    "c 0.025,0 0.058,0 0.076,0 0.192,0 0.375,-0.021 "
    "0.56,-0.021 0.195,0 0.384,0.021 0.563,0.021 "
    "0.032,0 0.058,0 0.083,0 v -0.034 "
    "c 17.192,-0.32 36.207,-7.446 54.622,-14.369 "
    "14.799,-5.553 30.119,-11.31 41.794,-12.476 "
    "l 1.202,-0.116 1.077,0.357 "
    "c 3.622,1.193 10.568,4.903 15.489,8.271 "
    "l 6.807,4.66 L 657.5,641.117 V 176.744 "
    "l -106.512,-51.097 -6.807,4.655 "
    "c -4.921,3.368 -11.867,7.082 -15.489,8.283 "
    "l -1.077,0.354 -1.202,-0.123 "
    "c -11.675,-1.157 -26.995,-6.925 -41.794,-12.484 "
    "-18.415,-6.918 -37.43,-14.042 -54.622,-14.36 "
    "v -0.032 c -0.025,0 -0.051,0 -0.083,0 "
    "-0.18,0 -0.368,0.011 -0.563,0.011 "
    "-0.185,-0.001 -0.368,-0.012 -0.56,-0.012 z"
)
_DOME_PC_VIEWBOX = 850.39371
_DOME_PC_TRANSLATE_X = 0.246


# On calcule les formes du Dome normalisees en 500x500.
# Compute normalized 500x500 Dome shapes.

_dome_cp_path = _rescale_dome_path(
    _DOME_CP_RAW_PATH, _DOME_CP_VIEWBOX,
)
_dome_sv_path = _rescale_dome_path(
    _DOME_SV_RAW_PATH, _DOME_SV_VIEWBOX,
    group_translate_x=_DOME_SV_TRANSLATE_X,
)
_dome_sf_path = _rescale_dome_path(
    _DOME_SF_RAW_PATH, _DOME_SF_VIEWBOX,
    group_translate_x=_DOME_SF_TRANSLATE_X,
    group_translate_y=_DOME_SF_TRANSLATE_Y,
)
_dome_se_path = _rescale_dome_path(
    _DOME_SE_RAW_PATH, _DOME_SE_VIEWBOX,
    group_translate_x=_DOME_SE_TRANSLATE_X,
    group_translate_y=_DOME_SE_TRANSLATE_Y,
)
_dome_xp_path = _rescale_dome_path(
    _DOME_XP_RAW_PATH, _DOME_XP_VIEWBOX,
    group_translate_x=_DOME_XP_TRANSLATE_X,
)
_dome_pj_path = _rescale_dome_path(
    _DOME_PJ_RAW_PATH, _DOME_PJ_VIEWBOX,
    group_translate_x=_DOME_PJ_TRANSLATE_X,
    group_translate_y=_DOME_PJ_TRANSLATE_Y,
)
_dome_gp_path = _rescale_dome_path(
    _DOME_GP_RAW_PATH, _DOME_GP_VIEWBOX,
    group_translate_x=_DOME_GP_TRANSLATE_X,
    group_translate_y=_DOME_GP_TRANSLATE_Y,
)
_dome_pc_path = _rescale_dome_path(
    _DOME_PC_RAW_PATH, _DOME_PC_VIEWBOX,
    group_translate_x=_DOME_PC_TRANSLATE_X,
)


# On ajoute les formes du Dome au dictionnaire.
# Add Dome shapes to the dictionary.

ALL_SHAPES["dome_cp"] = {
    "name": "Compétence (Dôme)",
    "description": "Étoile organique — Le Dôme CP",
    "path": _dome_cp_path,
}

ALL_SHAPES["dome_sv"] = {
    "name": "Savoir (Dôme)",
    "description": "Cercle — Le Dôme SV",
    "path": _dome_sv_path,
}

ALL_SHAPES["dome_sf"] = {
    "name": "Savoir-faire (Dôme)",
    "description": "Forme organique — Le Dôme SF",
    "path": _dome_sf_path,
}

ALL_SHAPES["dome_se"] = {
    "name": "Savoir-être (Dôme)",
    "description": "Rectangle arrondi — Le Dôme SE",
    "path": _dome_se_path,
}

ALL_SHAPES["dome_xp"] = {
    "name": "Expérience (Dôme)",
    "description": "Hexagone allongé — Le Dôme XP",
    "path": _dome_xp_path,
}

ALL_SHAPES["dome_pj"] = {
    "name": "Projet (Dôme)",
    "description": "Hexagone pointu — Le Dôme PJ",
    "path": _dome_pj_path,
}

ALL_SHAPES["dome_gp"] = {
    "name": "Groupe (Dôme)",
    "description": "Forme organique fluide — Le Dôme GP",
    "path": _dome_gp_path,
}

ALL_SHAPES["dome_pc"] = {
    "name": "Parcours (Dôme)",
    "description": "Bouclier à encoches — Le Dôme PC",
    "path": _dome_pc_path,
}


# La forme par defaut si aucune n'est choisie.
# Default shape if none is selected.
DEFAULT_SHAPE_KEY = "starburst"
